//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap
    {
        public int ID { get; set; }
        public string KitapAdi { get; set; }
        public Nullable<int> Yazarİd { get; set; }
        public Nullable<int> sayfasayisi { get; set; }
    
        public virtual yazar yazar { get; set; }
    }
}
